/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adupintar.client;

import com.sun.glass.events.KeyEvent;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import object.ChatMessage;

/**
 *
 * @author fendy
 */
public class Chat extends javax.swing.JFrame {

    private final String friendUsername;
    private final ChatListener listener;
    
    /**
     * Creates new form Chat
     * @param friendUsername
     * @param listener
     */
    public Chat(String friendUsername, ChatListener listener) {
        initComponents();
        
        this.friendUsername = friendUsername;
        this.setChatWith(friendUsername.equals("") ? "PUBLIC" : friendUsername);
        
        this.listener = listener;
        this.listener.addChatWith(friendUsername, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaChat = new javax.swing.JTextArea();
        txtBoxChatToSend = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblChatWith = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        txtAreaChat.setEditable(false);
        txtAreaChat.setColumns(20);
        txtAreaChat.setLineWrap(true);
        txtAreaChat.setRows(5);
        jScrollPane1.setViewportView(txtAreaChat);

        txtBoxChatToSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBoxChatToSendKeyPressed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblChatWith.setText("Chat with - Someone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBoxChatToSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSend))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChatWith)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblChatWith)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBoxChatToSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.listener.removeChat(this.friendUsername);
    }//GEN-LAST:event_formWindowClosed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        try {
            String message = txtBoxChatToSend.getText() + "\n";
            
            ChatServerConnection connection = ChatServerConnection.getInstance();
            ObjectOutputStream oos = connection.getOos();
            
            oos.writeObject(new ChatMessage(Credentials.getInstance().getUsername(), this.friendUsername, message));
            oos.reset();
            
            txtBoxChatToSend.setText("");
        } catch (IOException ex) {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void txtBoxChatToSendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoxChatToSendKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnSend.doClick();
        }
    }//GEN-LAST:event_txtBoxChatToSendKeyPressed

    /**
     * @param args the command line arguments
     */
    public void showForm() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChatWith;
    private javax.swing.JTextArea txtAreaChat;
    private javax.swing.JTextField txtBoxChatToSend;
    // End of variables declaration//GEN-END:variables

    private void setChatWith(String friendUsername) {
        lblChatWith.setText("Chat with - " + friendUsername);
    }
    
    public void appendMessage(String msg) {
        this.txtAreaChat.append(msg);
    }
}
