/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adupintar.client;

import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.WindowConstants;
import object.AddFriendData;
import object.RequestFriendData;
import object.Response;
import object.ResponseFriendData;

/**
 *
 * @author fendy
 */
public class FriendList extends javax.swing.JFrame {

    /**
     * Creates new form FriendList
     */
    public FriendList() throws IOException, ClassNotFoundException {
        initComponents();
        
        this.loadFriendData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listFriends = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBoxSearchUsrename = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listFriends.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listFriendsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listFriends);

        jLabel1.setText("Your Friend List");

        btnAdd.setText("Add Friend");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Username");

        txtBoxSearchUsrename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBoxSearchUsrenameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBoxSearchUsrename)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBoxSearchUsrename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listFriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFriendsMouseClicked
        if (evt.getClickCount() == 2) {
            Rectangle r = listFriends.getCellBounds(0, listFriends.getLastVisibleIndex());
            if (r != null && r.contains(evt.getPoint())) {
                int idx = listFriends.locationToIndex(evt.getPoint());
                String friendUsername = (String) listFriends.getModel().getElementAt(idx);
                if (idx == 0) friendUsername = "";
                Chat chatWindow = new Chat(friendUsername, Manager.getChatListener());
                chatWindow.showForm();
            }
        }
    }//GEN-LAST:event_listFriendsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String friendUsername = txtBoxSearchUsrename.getText();
            
            ServerConnection connection = ServerConnection.getInstance();
            ObjectInputStream ois = connection.getOis();
            ObjectOutputStream oos = connection.getOos();
            
            AddFriendData request = new AddFriendData(friendUsername);
            oos.writeObject(request);
            oos.reset();
            
            Response response = (Response) ois.readObject();
            
            int responseCode = response.getResponseCode();
            String responseString = response.getResponseString();
            if (responseCode == 200) {
                JOptionPane.showMessageDialog(null, "Friend Added!");
                
                this.loadFriendData();
            } else if (responseCode == 400){
                JOptionPane.showMessageDialog(null, "Error adding friend! " + responseString);
            }
        } catch (IOException ex) {
            Logger.getLogger(FriendList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FriendList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtBoxSearchUsrenameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoxSearchUsrenameKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnAdd.doClick();
        }
    }//GEN-LAST:event_txtBoxSearchUsrenameKeyPressed

    public void showForm() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listFriends;
    private javax.swing.JTextField txtBoxSearchUsrename;
    // End of variables declaration//GEN-END:variables

    private void loadFriendData() throws IOException, ClassNotFoundException {
        DefaultListModel model = new DefaultListModel();
        listFriends.setModel(model);
        model.addElement("PUBLIC");
        
        ServerConnection connection = ServerConnection.getInstance();
        if (connection != null) {
            ObjectOutputStream oos = connection.getOos();
            ObjectInputStream ois = connection.getOis();

            RequestFriendData request = new RequestFriendData("list");
            oos.writeObject(request);
            oos.reset();

            ResponseFriendData response = (ResponseFriendData) ois.readObject();
            ArrayList<String> friendList = response.getFriendList();

            for (String friend : friendList) {
                model.addElement(friend);
            }
        } else {
            JOptionPane.showMessageDialog(null, "You've been logged out!");
        }
    }
    
}
