/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adupintar.client;

import com.mysql.jdbc.StringUtils;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import object.LogInData;
import object.RequestSetUsername;
import object.Response;

/**
 *
 * @author fendy
 */
public class Login extends javax.swing.JFrame {

    private final JFrame parent;
    
    /**
     * Creates new form Login
     * @param parent
     */
    public Login(JFrame parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBoxUsername = new javax.swing.JTextField();
        txtBoxPassword = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Login");

        jLabel2.setText("Username ");

        jLabel3.setText("Password");

        txtBoxUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBoxUsernameKeyPressed(evt);
            }
        });

        txtBoxPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBoxPasswordKeyPressed(evt);
            }
        });

        btnSignup.setText("Sign Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSignup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogin))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(23, 23, 23)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBoxUsername)
                                .addComponent(txtBoxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBoxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBoxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignup)
                    .addComponent(btnLogin))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        Signup signupForm = new Signup(this);
        signupForm.showForm();
        this.setVisible(false);
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtBoxUsername.getText();
        char[] password = txtBoxPassword.getPassword();
        String pwd = String.copyValueOf(password);
        if (StringUtils.isEmptyOrWhitespaceOnly(username))
            JOptionPane.showMessageDialog(null, "Username wajib diisi!");
        else if(StringUtils.isEmptyOrWhitespaceOnly(pwd))
            JOptionPane.showMessageDialog(null, "Password wajib diisi!");
        else{
            try {
                LogInData data = new LogInData(username, pwd);
                ServerConnection connection = ServerConnection.getInstance();
                ObjectOutputStream oos = connection.getOos();
                oos.writeObject(data);
                oos.reset();
                
                ObjectInputStream ois = connection.getOis();
                Response response = (Response) ois.readObject();
                
                if (response.getResponseCode() == 200) {
                    Credentials.create(username);
                    this.logInToChatServer();
                    this.logInToGameServer();
                    
                    Play playForm = new Play(this, 10);
                    playForm.showForm();
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Login salah!");
                }
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (this.parent != null) {
            this.parent.setVisible(true);
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosed

    private void txtBoxUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoxUsernameKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnLogin.doClick();
        }
    }//GEN-LAST:event_txtBoxUsernameKeyPressed

    private void txtBoxPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoxPasswordKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnLogin.doClick();
        }
    }//GEN-LAST:event_txtBoxPasswordKeyPressed

    public void showForm() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtBoxPassword;
    private javax.swing.JTextField txtBoxUsername;
    // End of variables declaration//GEN-END:variables

    private void logInToChatServer() throws IOException, ClassNotFoundException {
        ChatServerConnection.setHost("localhost");
        ChatServerConnection.setPort(2525);
        
        ChatServerConnection.connect();
        ChatServerConnection connection = ChatServerConnection.getInstance();
        ObjectOutputStream oos = connection.getOos();
        ObjectInputStream ois = connection.getOis();
        
        Credentials cred = Credentials.getInstance();
        if (cred != null) {
            oos.writeObject(new RequestSetUsername(cred.getUsername()));
            oos.reset();
            
            Response response = (Response) ois.readObject();
            if (response.getResponseCode() != 200) {
                JOptionPane.showMessageDialog(null, "Error occured please restart the program");
                
                System.exit(1);
            } else {
                ChatListener listener = new ChatListener();
                Thread t = new Thread(listener);
                t.start();
                
                Manager.setChatListener(listener);
            }
        }
    }

    private void logInToGameServer() throws IOException, ClassNotFoundException {
        GameServerConnection.setHost("localhost");
        GameServerConnection.setPort(4747);
        GameServerConnection.connect();
        
        GameServerConnection connection = GameServerConnection.getInstance();
        ObjectOutputStream oos = connection.getOos();
        ObjectInputStream ois = connection.getOis();
        
        Credentials cred = Credentials.getInstance();
        if (cred != null) {
            oos.writeObject(new RequestSetUsername(cred.getUsername()));
            oos.reset();
            
            Response response = (Response) ois.readObject();
            if (response.getResponseCode() != 200) {
                JOptionPane.showMessageDialog(null, "Error occured please restart the program");
                
                System.exit(1);
            }
        }
    }
    
}
