/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adupintar.client;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import object.RequestSetUsername;
import object.Response;

/**
 *
 * @author Fendy
 */
public class QuizOverview extends javax.swing.JFrame {
    
    private Play parent;
    
    /**
     * Creates new form QuizOverview
     * @param enemyUsername
     * @param rounds
     * @param parent
     */
    public QuizOverview(String enemyUsername, int rounds, Play parent) {
        this.parent = parent;
        initComponents();
        
        lblEnemy.setText("Enemy: " + enemyUsername);
        lblRounds.setText("Rounds: " + rounds);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEnemy = new javax.swing.JLabel();
        lblRounds = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Quiz Time!!!");

        lblEnemy.setText("Enemy: Username");

        lblRounds.setText("Rounds: #number");

        lblFormat.setText("Format: classic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblEnemy)
                    .addComponent(lblRounds)
                    .addComponent(jLabel4)
                    .addComponent(lblFormat))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblEnemy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRounds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFormat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.parent.setVisible(true);
        
        GameServerConnection connection = GameServerConnection.getInstance();
        ObjectOutputStream oos = connection.getOos();
        ObjectInputStream ois = connection.getOis();
        
        Credentials cred = Credentials.getInstance();
        if (cred != null) {
            try {
                oos.writeObject(new RequestSetUsername(cred.getUsername()));
                oos.reset();
            } catch (IOException ex) {
                Logger.getLogger(QuizOverview.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public void showForm() {

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEnemy;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblRounds;
    // End of variables declaration//GEN-END:variables
}
